-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgA3LAJgrAezA9FqJE
NkS6p2yQWyBFGNDnR4wtRIZWfECgCgYIKoZIzj0DAQehRANCAAQoM7+a9GPEUHSR
SkSwFeFNg3cCnElfl95/Swb/RzQD3qiLrbwccwTRUvYVICVXT8+n1h/qql9nU8SX
f2av1kaM
-----END PRIVATE KEY-----