version: '1'
services:
  
  mysql:
    image: library/mysql:5.6.51
    container_name: mysql
    # platform: linux/x86_64
    ports:
      - 3306:3306
    privileged: true
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: Gptserver@.#$&2023
      TZ: Asia/Shanghai
    volumes:
      - ./mysql/my.cnf:/etc/my.cnf
      #- ./mysql/mysql.sock:/var/lib/mysql/mysql.sock
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/logs:/var/log/mysql
      - /etc/localtime:/etc/localtime
    networks:
      app_network:
        aliases:
          - mysql

  sdwebui:
    image: universonic/stable-diffusion-webui:latest
    container_name: sdwebui
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./sdwebui/extensions:/app/stable-diffusion-webui/extensions
      - ./sdwebui/models:/app/stable-diffusion-webui/models
      - ./sdwebui/outputs:/app/stable-diffusion-webui/outputs
      - ./sdwebui/localizations:/app/stable-diffusion-webui/localizations
    entrypoint: ["/app/entrypoint.sh", "--update-check", "--xformers", "--listen", "--port", "8080"]
    command: ["--medvram"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
    condition: "$SDWEBUI_ENABLED"
    networks:
      app_network:
        aliases:
          - sdwebui


# docker run --gpus all --restart unless-stopped -p 8080:8080 -v 
# /my/own/datadir/extensions:/app/stable-diffusion-webui/extensions -v 
# /my/own/datadir/models:/app/stable-diffusion-webui/models -v 
# /my/own/datadir/outputs:/app/stable-diffusion-webui/outputs -v 
# /my/own/datadir/localizations:/app/stable-diffusion-webui/localizations 
# --name stable-diffusion-webui -d universonic/stable-diffusion-webui

     
networks:
  # app_network:
  #   ipam:
  #     driver: default
  #     config:
  #       - subnet: "192.168.50.0/24"
  #         gateway: "192.168.50.20"
  app_network:

